### ISSUE TITLE
BSD licence with firmware

### ISSUE THREAD

**Issue by sjkklein** [jdesbonnet/LPC810_SousVide#1]
Hey there!

I am using an edited version of your one wire code in a project and regret it now that I read the license. The license stipulates that a copy must be distributed with binary versions of the code. That is kindof a big ask with firmware, since the license would need to somehow be accessible in the image on the device itself. Disclaimer: I am not a lawyer, this is my interpretation of the license. 

I am assuming you were using the BSD in order to allow the copying and use of your code in others work. It seems BSD is not the best choice in the embedded realm though. 

I am hoping it is possible for you to alter the license to the ISC license so that I can use your one-wire code in my project!

https://opensource.org/licenses/ISC

Either way, let me know.

**Comment by jdesbonnet** [comment]
oh sorry, I doubt I ever intended for any inconvenient restrictions.  Let me
take a look at the licence... I just must have copied/pasted without reading too
carefully.

Joe

**Comment by jdesbonnet** [comment]
License changed to ISC as requested.

**Comment by sjkklein** [comment]
Thank you so much!
